Sodexo Peru/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SDX_Numero_de_documento__c</fullName>
        <label>Número de documento</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDX_Tipo_Administracion__c</fullName>
        <label>Tipo Administración</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Centralizada</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SDX_Tipo_de_documento__c</fullName>
        <label>Tipo de documento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RUC</fullName>
                    <default>true</default>
                    <label>RUC</label>
                </value>
                <value>
                    <fullName>DNI</fullName>
                </value>
                <value>
                    <fullName>Extranjero</fullName>
                </value>
                <value>
                    <fullName>ID exterior</fullName>
                    <isActive>false</isActive>
                    <label>ID exterior</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SDX_Tipo_de_mercado__c</fullName>
        <label>Tipo de mercado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Libre</fullName>
                </value>
                <value>
                    <fullName>Capturado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sodexo Peru/src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Complejo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complejo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Documentacion_Entregada__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Documentación Entregada</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Encuesta_Enviada__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Encuesta Enviada</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Envia_Correo_Onboarding__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Envia Correo Onboarding</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Excepcion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Excepción</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Excepcion_regularizada__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Excepción regularizada</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kit_Enviaddo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kit Enviaddo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OnBoarding_Exitoso__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OnBoarding Exitoso</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sodexo Peru/src/classes/SDXAGIL_WsContrato_Controller_Test.cls
/****************************
  Desarrollado por: Nectia
  Autor: Rodrigo López (RL)
  Proyecto: Sodexo AGIL
  Descripción: Clase Test de SDXAGIL_WsContrato_Controller y SDXAGIL_ClientRegistrarResp_JSON
 
  ---------------------------------------------------------------------------------
  No. Fecha                Autor                     Descripción
  ------ ---------- ---------------------------------------------------------------
  1.0 14-03-2021            RL                   Creación de Clase.
 *****************************/

@isTest
public class SDXAGIL_WsContrato_Controller_Test  {
	@TestSetup 
	static void setup(){
		Account cuenta = new Account(
		  Name = 'ARSD',								// Razón Social
		  NumberOfEmployees = 44,                       // Empleados
		  SDX_Tipo_de_documento__c = 'RUC',             // Tipo de documento
		  SDX_Numero_de_documento__c = '11111111113',   // Número de documento
		  SDX_Tipo_Administracion__c = 'Individual',    // Tipo Administración
		  Industry = 'Other',                           // Sector
		  SDX_Tipo_de_mercado__c = 'Libre'				// Tipo de mercado
		);
		insert cuenta;

		Contract sobj = new Contract(
		  StartDate = Date.valueOf('2021-04-06'),       // Fecha de inicio del contrato
		  AccountId = cuenta.Id,                        // Razón Social
		  Status = 'En Creación',                       // Estado
		  Complejo__c = false,                          // Complejo
		  Envia_Correo_Onboarding__c = false,           // Envia Correo Onboarding
		  OnBoarding_Exitoso__c = false,                // OnBoarding Exitoso
		  Excepcion__c = false,                         // Excepción
		  Documentacion_Entregada__c = false,           // Documentación Entregada
		  Excepcion_regularizada__c = false,            // Excepción regularizada
		  Kit_Enviaddo__c = false,                      // Kit Enviaddo
		  Encuesta_Enviada__c = false					// Encuesta enviada
		);
		insert sobj;
	}

	//Test de Error - Error 001
	static testmethod void WsContrato_Controller_Test1() {
		Test.startTest();

		Contract cont = [SELECT Id, Name, Respuesta_Exitosa_de_Integracion__c FROM Contract WHERE Account.Name = 'ARSD'];
		
		Test.setMock(HttpCalloutMock.class, new SDXAGIL_MockHttpResponseGenerator());
				
		PageReference pref = Page.SDXAGIL_WsContrato;
		Test.setCurrentPage(pref);
		pref.getParameters().put('id', cont.Id);
		ApexPages.StandardController apst=new ApexPages.StandardController(cont);
		SDXAGIL_WsContrato_Controller wsContrato = new SDXAGIL_WsContrato_Controller(apst);
		wsContrato.guardarRespuesta();
		wsContrato.redirect();

		wsContrato = new SDXAGIL_WsContrato_Controller(apst);

		System.assert(cont.Respuesta_Exitosa_de_Integracion__c == false, true);

		Test.stopTest();
	}

	//Test de Error al Obtener Token
	static testmethod void WsContrato_Controller_Test2() {
		Test.startTest();

		Contract cont = [SELECT Id, Name, Respuesta_Exitosa_de_Integracion__c FROM Contract WHERE Account.Name = 'ARSD'];
		
		Test.setMock(HttpCalloutMock.class, new SDXAGIL_MockHttpResponseTokenError());
				
		PageReference pref = Page.SDXAGIL_WsContrato;
		Test.setCurrentPage(pref);
		pref.getParameters().put('id', cont.Id);
		ApexPages.StandardController apst=new ApexPages.StandardController(cont);
		SDXAGIL_WsContrato_Controller wsContrato = new SDXAGIL_WsContrato_Controller(apst);
		wsContrato.guardarRespuesta();
		wsContrato.redirect();

		wsContrato = new SDXAGIL_WsContrato_Controller(apst);

		System.assert(cont.Respuesta_Exitosa_de_Integracion__c == false, true);

		Test.stopTest();
	}

	//Test de Error al Obtener datos del Contrato
	static testmethod void WsContrato_Controller_Test3() {
		Test.startTest();

		Contract cont = [SELECT Id, Name, Respuesta_Exitosa_de_Integracion__c FROM Contract WHERE Account.Name = 'ARSD'];
		
		PageReference pref = Page.SDXAGIL_WsContrato;
		Test.setCurrentPage(pref);
		pref.getParameters().put('test', null);
		ApexPages.StandardController apst=new ApexPages.StandardController(cont);
		SDXAGIL_WsContrato_Controller wsContrato = new SDXAGIL_WsContrato_Controller(apst);
		wsContrato.guardarRespuesta();
		wsContrato.redirect();

		wsContrato = new SDXAGIL_WsContrato_Controller(apst);

		System.assert(cont.Respuesta_Exitosa_de_Integracion__c == false, true);

		Test.stopTest();
	}

	//Test de Error al Obtener datos del Contrato
	static testmethod void WsContrato_Controller_Test4() {
		Test.startTest();

		Contract cont = [SELECT Id, Name, Respuesta_Exitosa_de_Integracion__c FROM Contract WHERE Account.Name = 'ARSD'];
		
		Test.setMock(HttpCalloutMock.class, new SDXAGIL_MockHttpResponseEx());

		PageReference pref = Page.SDXAGIL_WsContrato;
		Test.setCurrentPage(pref);
		pref.getParameters().put('id', cont.Id);
		ApexPages.StandardController apst=new ApexPages.StandardController(cont);
		SDXAGIL_WsContrato_Controller wsContrato = new SDXAGIL_WsContrato_Controller(apst);
		wsContrato.guardarRespuesta();
		wsContrato.redirect();

		wsContrato = new SDXAGIL_WsContrato_Controller(apst);

		System.assert(cont.Respuesta_Exitosa_de_Integracion__c == false, true);

		Test.stopTest();
	}

	//Test de Error - Código 400
	static testmethod void WsContrato_Controller_Test5() {
		Test.startTest();

		Contract cont = [SELECT Id, Name, Respuesta_Exitosa_de_Integracion__c FROM Contract WHERE Account.Name = 'ARSD'];
		
		Test.setMock(HttpCalloutMock.class, new SDXAGIL_MockHttpResponseError());

		PageReference pref = Page.SDXAGIL_WsContrato;
		Test.setCurrentPage(pref);
		pref.getParameters().put('id', cont.Id);
		ApexPages.StandardController apst=new ApexPages.StandardController(cont);
		SDXAGIL_WsContrato_Controller wsContrato = new SDXAGIL_WsContrato_Controller(apst);
		wsContrato.guardarRespuesta();
		wsContrato.redirect();

		wsContrato = new SDXAGIL_WsContrato_Controller(apst);

		System.assert(cont.Respuesta_Exitosa_de_Integracion__c == false, true);

		Test.stopTest();
	}

	//Test de Error - Código 400
	static testmethod void WsContrato_Controller_Test6() {
		Test.startTest();

		Contract cont = [SELECT Id, Name, Respuesta_Exitosa_de_Integracion__c FROM Contract WHERE Account.Name = 'ARSD'];
		
		Test.setMock(HttpCalloutMock.class, new SDXAGIL_MockHttpResponseToken());

		PageReference pref = Page.SDXAGIL_WsContrato;
		Test.setCurrentPage(pref);
		pref.getParameters().put('id', cont.Id);
		ApexPages.StandardController apst=new ApexPages.StandardController(cont);
		SDXAGIL_WsContrato_Controller wsContrato = new SDXAGIL_WsContrato_Controller(apst);
		wsContrato.guardarRespuesta();
		wsContrato.redirect();

		wsContrato = new SDXAGIL_WsContrato_Controller(apst);

		System.assert(cont.Respuesta_Exitosa_de_Integracion__c == false, true);

		Test.stopTest();
	}

	//Test de Error - Enviando Contrato en estado previo a "En Creación"
	static testmethod void WsContrato_Controller_Test7() {
		Test.startTest();

		Contract cont = [SELECT Id, Name, Respuesta_Exitosa_de_Integracion__c FROM Contract WHERE Account.Name = 'ARSD'];
		cont.Status = 'Draft';
		update cont;
		
		PageReference pref = Page.SDXAGIL_WsContrato;
		Test.setCurrentPage(pref);
		pref.getParameters().put('id', cont.Id);
		ApexPages.StandardController apst=new ApexPages.StandardController(cont);
		SDXAGIL_WsContrato_Controller wsContrato = new SDXAGIL_WsContrato_Controller(apst);
		wsContrato.guardarRespuesta();
		wsContrato.redirect();

		wsContrato = new SDXAGIL_WsContrato_Controller(apst);

		System.assert(cont.Respuesta_Exitosa_de_Integracion__c == false, true);

		Test.stopTest();
	}

	//Test de Error - No Reenviar Contrato ya enviado"
	static testmethod void WsContrato_Controller_Test8() {
		Test.startTest();

		Contract cont = [SELECT Id, Name, Respuesta_Exitosa_de_Integracion__c FROM Contract WHERE Account.Name = 'ARSD'];
		cont.Status = 'In Approval Process';
		cont.Respuesta_Exitosa_de_Integracion__c = true;
		update cont;
		
		PageReference pref = Page.SDXAGIL_WsContrato;
		Test.setCurrentPage(pref);
		pref.getParameters().put('id', cont.Id);
		ApexPages.StandardController apst=new ApexPages.StandardController(cont);
		SDXAGIL_WsContrato_Controller wsContrato = new SDXAGIL_WsContrato_Controller(apst);
		wsContrato.guardarRespuesta();
		wsContrato.redirect();

		wsContrato = new SDXAGIL_WsContrato_Controller(apst);

		System.assert(cont.Respuesta_Exitosa_de_Integracion__c == true, true);

		Test.stopTest();
	}
}